---
title:  'My Starter Report'  
subtitle: 'This is an example Scrivener starter project'  
author: Paul Brandt  
affiliation: TNO  
version:    
category: MakeYourOwnCategoriesHere  
ack: <!-- Remove the comment markers to include an acknowledgement, e.g., This work was supported by the EC, through the RECAP project, part of the Interreg IVB NWE Programme. -->    
tags: <!-- tagword, or a descriptive tag, each tag separated by comma -->  
bibliography: src/bib/bibliography.bib  
csl: templates/basic-reference-style.csl  
abstract: |  
    On making use of a YAML-block, make this your very first document file such that Scrivener will compile this document page as the very first text in the resulting (generated) file. The template supports the use of an abstract that is copied into the LaTeX `abstract` variable that you can find the basic tex template.  
    You can use newlines, but remember this is a standard YAML-format, hence use two spaces before the newline, and four spaces to begin your new line as has been done with this line.
    
...

This is probably my first, and only, chapter in this document. This is an MMD-format text: multi-markdown format, which is very easy to read and write, and is remarkably expressive for encoding formats, e.g., a list:

* with bullits
* two lines of bullits;
* no, three lines!

Note that you can find an MMD cheat sheet in the binder of this Scrivener project. However, you do not need to make use of mmd; Scrivener is also capable of some basic formatting so that you can use it similar to what you are used in Word. 

